config/routes.rb
ProjectFighter::Application.routes.draw do
  get "projects/index"

  devise_for :users
  root :to => 'home#index'

  namespace :admin do
    resources :users
  end
  resources :projects do
    resources :tasks do
      resources :time_records do
        member do
          put :stoptimerecord
          put :updatecomment
        end
      end
      member do
        put :update_status
        post :startwork
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role?('admin')
        can :manage, :all
    end
    if user.has_role?('user')
      can :read, Project, :owner => user
      can :create, Project 
      can :update, Project, :owner=>user
      can :read, Task, :project => { :owner => user }
      can :update, Task, :project => {:owner => user }
      can :update_status, Task, :project => {:owner => user }
      can :startwork, Task, :project => {:owner => user}
    end
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :title, :note
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :slug, :title, :description, :owner, :tasks
  belongs_to :owner, :class_name=>'User'
  has_many :tasks

  def no_of_tasks?(status)
    self.tasks.where(:status => status).count
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :role, :description
  has_and_belongs_to_many :users, :autosave => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :title, :description, :project, :status, :timerecords
  belongs_to :project
  has_many :time_records

  def all_stopped?
    if self.time_records.where(:started=>true).count > 0
      false
    else
      true
    end
  end

  def total_work_time?
    total_time=0
    self.time_records.where(:started => false).all.each do |t|
      total_time+=TimeDifference.between(t.created_at,t.updated_at).in_seconds
    end

    total_time.round
  end
end

app/models/time_record.rb
class TimeRecord < ActiveRecord::Base
  attr_accessible :task, :created_at, :updated_at, :started, :first, :last
  belongs_to :task
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :roles, :owned_projects
  has_and_belongs_to_many :roles, :autosave => true
  has_many :owned_projects, :foreign_key=>'owner_id', :class_name=>'Project'

  # attr_accessible :title, :body
  def has_role?(rolename)
    self.roles.exists?(:role=>rolename)
  end
  def roles_for_select
    arr=[]
    self.roles.select('id').all.each do |a|
      arr << a.id
    end
    arr
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  #load_and_authorize_resource

  def index
    @users=User.all
    respond_to do |format|
      format.html
      format.json { render :json => @users }
    end
  end

  def edit
    @user=User.find(params[:id])
    @roles=Role.all
    Rails.logger.debug(@user)
    respond_to do |format|
      format.html
    end
  end

  def update
    @user=User.find(params[:id])
    @user.name=params[:user][:name]
    @user.email=params[:user][:email]
    @user.roles=Role.find(params[:user][:roles_for_select].reject!{|v| v.empty?})
    @user.deactivated=params[:user][:deactivated]
    respond_to do |format| 
      if @user.save
        format.html { redirect_to(admin_users_path, :notice=>'User %{user} success updated' % {:user=>@user.name}) }
        format.json {head :no_content}
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @projects = current_user.owned_projects
  end

  def show
    @project=Project.find(params[:id])
  end

  def new
  end

  def create
    @project=Project.new
    @project.owner=current_user
    @project.slug=params[:project][:slug]
    @project.title=params[:project][:title]
    @project.description=params[:project][:description]
    respond_to do |format|
      if @project.save
        format.html { redirect_to(projects_path, :notice => 'Project %{slug} created successfully!' % { :slug=>@project.slug})}
        format.json { header :no_content }
      else
        format.html { render :action => :new }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  def show
    @task=Task.find(params[:id])
  end

  def startwork
    @project=Project.find(params[:project_id])
    @task=@project.tasks.find(params[:id])
    if @task.time_records.where(:first => true).count > 0
      t=TimeRecord.create(:task=>@task, :started=>true, :first=>false)
    else
      t=TimeRecord.create(:task=>@task, :started=>true, :first=>true)
    end
    @task.status='in_progress'
    @task.save
    respond_to do |format|
      session[:action]='task_updated'
      session[:task_updated]=@task.id
      format.json { head :no_content }
    end
  end

  def update_status
    @project=Project.find(params[:project_id])
    @task=@project.tasks.find(params[:id])
    Rails.logger.debug(params);
    if params[:status]
      @task.status=params[:status]
    end
    respond_to do |format|
      if @task.save
        if @task.status=='new' or @task.status=='done'
          trecord=@task.time_records.where(:started=>true).first
          if trecord != nil
            trecord.started=false
            trecord.save
          end
        end
        if @task.status=='in_progress'
          if @task.time_records.all.count == 0
            TimeRecord.create(:task=>@task, :started=>true, :first=>true)
          else
            TimeRecord.create(:task=>@task, :started=>true, :first=>false)
          end
        end
        if @task.status=='done'
        end
        session[:action]='task_updated'
        session[:task_updated]=@task.id
        format.html { redirect_to(@project,:notice=>'Task updated')}
        format.json { head :no_content }
      else
        format.html {render :action => 'show' }
        format.json { render :json => @task.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/time_records_controller.rb
class TimeRecordsController < ApplicationController

  def stoptimerecord
    @project=Project.find(params[:project_id])
    @task=@project.tasks.find(params[:task_id])
    @timerecord=@task.time_records.find(params[:id])
    @timerecord.started=false
    @timerecord.touch
    respond_to do |format|
      if @timerecord.save
        session[:action]='task_updated'
        session[:task_updated]=@task.id
        format.json { head :no_content }
      else
        format.json { render :json => @timerecord.errors, :status => :nonprocessable_entity }
      end
    end
  end

  def updatecomment
    @project=Project.find(params[:project_id])
    @task=@project.tasks.find(params[:task_id])
    @timerecord=@task.time_records.find(params[:id])
    @timerecord.comment=params[:comment]
    respond_to do |format|
      if @timerecord.save
        session[:action]='task_updated'
        session[:task_updated]=@task.id
        format.json { head :no_content }
      else
        format.json { render :json => @timerecord.errors, :status => :nonprocessable_entity }
      end
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  def resource
    @resource ||= User.new
  end
  def devise_mapping
    @devise_mapping ||=Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/time_records_helper.rb
module TimeRecordsHelper
end

app/views/admin/users/edit.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>
<%= form_for @user, :url => { :action =>"update" } do |f| %>
  <div class="row">
    <div class="span9 page-header">
      <h2>Edit <%= @user.name %></h2>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, 'Name', :class=>'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :placeholder=>'Name', :class=>'span6'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, 'E-Mail', :class=>'control-label'%>
    <div class="controls">
      <%= f.text_field :email, :placeholder => 'E-Mail', :class=>'span6'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :roles, 'Roles', :class=>'control-label' %>
    <div class="controls">
      <%= f.collection_select(:roles_for_select, @roles, :id, :role, {}, {:class=>'span6',:multiple=>true}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :deativated, 'Deactivate?',:class=>'control-label' %>
    <%= f.check_box :deactivated %>
  </div>
  <div class="row">
    <div class="span9">
      <div class="pull-right">
        <%= link_to 'Cancel', admin_users_path, :class=>'btn' %>
        <%= f.button 'Save', :type=>'submit', :class=>'btn btn-primary btn-default'%>
      </div>
    </div>
  </div>
<%- end %>

app/views/admin/users/index.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>
<%- content_for :jscript do %>
  <%= javascript_include_tag controller_path %>
<%- end %>
<div class="container">
  <div class="row">
    <div class="span9" id="<%= '%{path}_%{action}' % {:path=>controller_path.sub(/\//,'_'),:action=>action_name} %>">
      <table class="table table-bordered table-striped table-hover table-condensed">
        <thead>
          <tr><th>Name</th><th>E-Mail</th><th>Created At</th></tr>
        </thead>
        <tbody>
          <%- for user in @users %>
            <tr class="<%- if user.deactivated %>error<%-end%>" data-edit-url="<%= url_for :controller => 'users' , :action => 'edit', :id => user %>">
              <td data-cell="true"><%= user.name %></td>
              <td data-cell="true"><%= user.email %></td>
              <td data-cell="true"><%= user.created_at %></td>
            </tr>
          <%- end %>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>

app/views/includes/_layout_navbar.html.erb
<div class="container">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'Projects', root_url, :class=>'brand'%>
        <div class="container nav-collapse">
          <ul class="nav">
            <%- if can? :read, Project %>
              <LI><%= link_to 'Projects', projects_path %></LI>
            <%- end %>
        	</ul>
          <ul class="nav pull-right">
		  	<%- if not user_signed_in? %>
            	<li><a href="#SignUpDialog" role="button" data-toggle="modal">Sign Up</a></LI>
            	<li class="divider-vertical"></LI>
            	<li class="dropdown">
          	  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sign In <strong class="caret"></strong></a>
            	<div class="dropdown-menu" style="padding:15px; padding-bottom:0px;">
              	<%= form_for(resource, :as => resource_name, :url => session_path(resource_name))  do |f| %>
                		<%= f.label :email, 'E-Mail' %>
                		<%= f.text_field :email, :placeholder=>'Username'%>
                		<%= f.label :password, 'Password'%>
                		<%= f.password_field :password, :placeholder => 'Password' %>
                		<%= button_tag 'Sign In', :type=>'submit', :class=>'btn btn-primary btn-default', :style=>"clear:left; width:100%"%>
            	  <%- end %>
            	</div>
            </LI>
            <%- else %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %> <strong class="caret"></strong></a>
              <ul class="dropdown-menu">
                <%- if can? :manage, :all %>
                  <li class="nav-header">Administration</li>
                  <li><%= link_to 'Users', admin_users_path %></li>
                  <li class="divider"></li>
                <%- end %>
              <%- if can? :create, Project %>
                <li class="nav-header">Actions</li>
                <li><%= link_to 'Create Project', new_project_path %></LI>
              <%- end %>
              <li class="divider"></li>
              <li><a href="#">Settings</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, :method=>'delete' %></LI>
            </ul>
          </li>
          <%- end %>
        </ul>
      </div>
  	</div>
  </div>
</div>
</div>
<%- if !user_signed_in? %>
<%= render 'includes/signup_dialog' %>
<%- end %>

app/views/includes/_signup_dialog.html.erb
<div id="SignUpDialog" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="SignUpDialogLabel" aria-hidden="true">
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
    <div class="modal-header">
      <h3 id="SignUpDialogLabel">Sign up</h3>
    </div>
    <div class="modal-body">
      <div class="span4">
        <%= f.label :name, 'Your Name'%>
        <%= f.text_field :name, :placeholder=>'Your Name', :class=>'span5' %>
        <%= f.label :email, 'E-Mail' %>
        <%= f.email_field :email, :placeholder => 'E-Mail', :class=>'span5' %>
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, :placeholder=>'Password', :class=>'span5' %>
        <%= f.label :password_confirmation, 'Confirm Password' %>
        <%= f.password_field :password_confirmation,  :placeholder=>'Confirm Password', :class=>'span5' %>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
      <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
  <%- end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectFighter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <%= content_for?(:navbar) ? yield(:navbar) :''%>
    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <%- if content_for?(:sidebar) %>
            <div class="span3">
              <div class="well">
                <%= yield(:sidebar) %>
              </div>
            </div>
          <%- end %>
        </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= content_for?(:jscript) ? yield(:jscript) : ''%>

  </body>
</html>

app/views/projects/_form.html.erb
        <div class="control-group">
          <%= f.label :slug, 'Slug', :class=>'control-label' %>
          <div class="controls">
            <%= f.text_field :slug, :placeholder=>'Slug', :class=>'span3' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :title, 'Title', :class=>'control-label' %>
          <div class="controls">
            <%= f.text_field :title, :placeholder=>'Title', :class=>'span5' %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :description, 'Description', :class=>'control-label'%>
          <div class="controls">
            <%= f.text_area :description, :class=>'span5', :placeholder=>'Description', :rows=>5, :cols=>78 %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls pull-right">
            <%= link_to 'Cancel', projects_path, :class=>'btn btn-cancel' %>
            <%= f.button 'Create', :class=>'btn btn-primary btn-default', :type=>'submit' %>
          </div>
        </div>
 

app/views/projects/_tasks.html.erb
<div class="row">
  <div class="span9">
    <div class="accordion" id="accordion_tasks_new" style="height:300px; overflow:auto;">
      <%- for task in @project.tasks.where(:status=>task_status).all do %>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_tasks_new" href="#task_<%= task.id %>"><%= task.title %></a>
          </div>
          <div class="accordion-body collapse<%- if session.has_key?('action') and session[:action]=='task_updated' and session[session[:action]]==task.id %>in<%-end%>" id="task_<%= task.id %>">
            <div class="accordion-inner project-task" data-url="<%= url_for [@project,task] %>">
              <div class="row">
                <div class="span2">
                  <ul class="nav nav-tabs nav-stacked">
                    <li class="active"><a href="#description_<%= task.id %>" data-toggle="tab">Details</a></li>
                    <li><a href="#time_records_<%= task.id %>" data-toggle="tab">Time Records</a></li>
                  </ul>
                </div>
                <div class="span6">
                  <div class="tab-content">
                    <div class="tab-pane active" id="description_<%= task.id %>">
                      <div class="row">
                        <div class="span6">
                          <div class="row">
                            <div class="span6">
                              <div class="control-group">
                                Total work time:<br/>
                                <span class="label label-info task_total_work_time"><%= task.total_work_time? %></span>
                             </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="span6">
                              <div class="control-group">
                                Status:<br/>
                                <%= select_tag(:status, options_for_select([['New','new'],['In Progress','in_progress'],['Done','done']],task.status),{:class=>'span3 task-status-changer','data-url'=>url_for(update_status_project_task_path(@project,task))}) %>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="tab-pane" id="time_records_<%= task.id %>">
                      <div class="row">
                        <div class="span6">
                          <%- if task.all_stopped? and task.status != 'done'%>
                            <button class="btn btn-small start_time_record" data-url="<%= url_for(startwork_project_task_path(@project,task))%>">Start Work</button>
                          <%- end %>
                          <table class="table table-condensed table-bordered">
                            <thead>
                              <tr>
                                <th>Work Started At</th>
                                <th>Work Ended At</th>
                                <th>Comment</th>
                              </tr>
                            </thead>
                            <tbody>
                              <%- for timerecord in task.time_records.order(:created_at).reverse_order.limit(5) %>
                                <tr>
                                  <td><%= timerecord.created_at %></td>
                                  <td>
                                    <%- if not timerecord.started %>
                                      <%=timerecord.updated_at %>
                                    <%- end %>
                                    <%- if timerecord.started %>
                                    <button data-url="<%= url_for(stoptimerecord_project_task_time_record_path(@project,task,timerecord))%>" class="btn btn-small stop-time-record">Stop</button>
                                  <%- end %>
                                  </td>
                                  <td>
                                    <%- if timerecord.comment.empty? %>
                                      <a href="#modal_comment_<%= task.id %>_<%= timerecord.id %>" data-toggle="modal">Click here to add a comment</a>
                                    <%- else %>
                                      <a href="#modal_comment_<%= task.id %>_<%= timerecord.id %>" data-toggle="modal" title="Click here to change comment"><%= timerecord.comment %></a>
                                    <%- end %>

                                    <div id="modal_comment_<%= task.id %>_<%= timerecord.id %>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="comment_for_<%=task.id%>_<%=timerecord.id%>" area-hidden="true">
                                      <div class="modal-header">
                                        <h3 id="comment_for_<%= task.id%>_<%=timerecord.id%>">Comment</h3>
                                      </div>
                                      <div class="modal-body">
                                        <div class="control-group">
                                          <%= label_tag('comment_'+task.id.to_s+'_'+timerecord.id.to_s, "Comment", :class=>'control-label') %>
                                          <div class="controls">
                                            <%= text_field_tag('comment_'+task.id.to_s+'_'+timerecord.id.to_s, timerecord.comment, :class=>'span5', :placeholder=>'Comment') %>
                                          </div>
                                        </div>
                                      </div>
                                      <div class="modal-footer">
                                        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                                        <button class="btn btn-primary btn-default update_comment_btn" data-dialog-parent="modal_comment_<%=task.id%>_<%=timerecord.id%>" data-update-url="<%= url_for(updatecomment_project_task_time_record_path(@project,task,timerecord))%>" data-dismiss="modal" aria-hidden="true">Save</button>
                                      </div>
                                    </div>
                                  </td>
                                </tr>
                              <%- end %>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%- end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>
<%- content_for :jscript do %>
  <%= javascript_include_tag controller_path %>
<%- end %>
<div class="container">
  <div class="row">
    <div class="span9 page-header">
      <h2>New Project</h2>
    </div>
  </div>
  <div class="row">
    <div class="span9">
      <%= form_for @project, :url => {:action=>'update'} do |f| %>
        <%= render :partial=>'form', :locals => { :f => f} %>
      <%- end %>
    </div>
  </div>
</div>

app/views/projects/includes/_my_projects.html.erb
<div class="row">
  <div class="span9">
    <DL>
      <%- for project in @projects %>
        <DT><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_project_path(project) %> <%= link_to project.title, project %></DT>
        <DD>
          <ul>
          <%- for task in project.tasks %>
              <li><%= link_to task.title, project_task_path(project,task) %></LI>
            <%- end %>
          </ul>
        </DD>
      <%- end %>
    </DL>
  </div>
</div>

app/views/projects/index.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>
<%- content_for :jscript do %>
  <%= javascript_include_tag controller_path %>
<%- end %>
<div class="row">
  <div class="span9">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#my_projects" data-toggle="tab">My Projects</a></LI>
      <li><a href="#work_projects" data-toggle="tab">Projects I am on</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="my_projects">
        <%= render :partial=>'projects/includes/my_projects' %>
      </div>
      <div class="tab-pane" id="work_projects">
        foo
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>
<%- content_for :jscript do %>
  <%= javascript_include_tag controller_path %>
<%- end %>
<div class="container">
  <div class="row">
    <div class="span9 page-header">
      <h2>New Project</h2>
    </div>
  </div>
  <div class="row">
    <div class="span9">
      <%= form_for @project, :url => {:action=>'create'} do |f| %>
        <%= render :partial=>'form', :locals => { :f => f} %>
      <%- end %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%- content_for :navbar do %>
  <%= render :partial => 'includes/layout_navbar' %>
<%- end %>
<%- content_for :jscript do %>
  <%= javascript_include_tag controller_path %>
<%- end %>
<%- if @project.owner == current_user %>
<%- content_for :sidebar do %>
  <UL class="nav nav-list">
    <LI class="nav-header">Tasks</LI>
    <LI><a href="#">Create new task</a></li>
  </ul>
<%- end %>
<%- end %>
<div class="row">
  <div class="span9">
    <div class="page-header">
      <h2><%= @project.title %></h2><div class="pull-right">Back</div>
      <small>Created At:&nbsp;<span class="date_convert_to_local"><%= @project.created_at.to_datetime.iso8601%></span></small>
    </div>
  </div>
</div>
<div class="row">
  <div class="span9">
    <a href="#">Create new task</a>
  </div>
</div>
<div class="row">
  <div class="span9">
    <ul class="nav nav-tabs">
    <li <%- if @project.no_of_tasks?('in_progress') >0 %>class="active"<%- end %>><a href="#tasks_in_progress" data-toggle="tab">In Progress</a></li>
    <LI<%- if @project.no_of_tasks?('in_progress') <=0 %> class="active"<%- end%>><a href="#tasks_in_new" data-toggle="tab">New</a></LI>
      <LI><a href="#tasks_in_done" data-toggle="tab">Done</a></LI>
    </UL>
    <div class="tab-content">
      <div class="tab-pane<%- if @project.no_of_tasks?('in_progress') > 0 %> active<%-end%>" id="tasks_in_progress">
        <%= render :partial => 'tasks', :locals => {:task_status => 'in_progress'} %>
      </div>
      <div class="tab-pane<%- if @project.no_of_tasks?('in_progress') <= 0%> active<%-end%>" id="tasks_in_new">
        <%= render :partial => 'tasks', :locals => { :task_status=>'new'} %>
      </div>
      <div class="tab-pane" id="tasks_in_done">
        <%= render :partial => 'tasks', :locals => {:task_status => 'done' }%>
      </div>
    </div>
  </div>
</div>